name: symbench-athens-client-dev
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - api4jenkins
    - pytest
    - black
    - pre-commit
    - isort
    - gremlinpython
    - tomark
    - --editable=git+https://github.com/symbench/uav-analysis.git#egg=uav-analysis
